all:
	@javac -cp ".:../mysql-connector-java-5.1.44-bin.jar" */*.java
	@javac -cp ".:../mysql-connector-java-5.1.44-bin.jar" *.java

clean:
	@rm -rf */*.class
	@rm -rf *.class

run:
	@java -cp ".:../mysql-connector-java-5.1.44-bin.jar" Main